from selenium import webdriver
from time import sleep
driver = webdriver.Chrome()
driver.get("https://www.amazon.in/")
sleep(5)
driver.maximize_window()
sleep(5)
driver.back()
sleep(5)
driver.forward()
sleep(5)
driver.refresh()
sleep(5)
driver.minimize_window()
sleep(5)
print("Name :",driver.name)
print("Title:", driver.title)
print("URL:", driver.current_url)
# driver.close()
driver.quit()

